version: 1.2.2
services:
  - cpanel
  - indexer
  - optimizer
  - search
  - historic-search
  - logwatcher
  - gateway
config:
  client.env: "demo"
  client.id: "EPISCMZV"
  client.license.key: "3961e63a-006d-4659-8f6c-53e9b379543e"
  cpanel.api.access.key: "token"
  cpanel.api.access.token: "c8bf035cefd11523822d6b6e1ea242d7edd77f9c"
  cpanel.gateway.server: "episilia-gateway:9002"
  datastore.s3.accesskey: "22ULBGAK7VEHIKDTNMBM"
  datastore.s3.secretkey: "Q0owaKYs5MHzOiLUOsi8tXwhiDS0p8gyzDCacLCUMgk"
  datastore.s3.bucket: "episilia-demo"
  datastore.s3.endpoint.url: "sgp1.digitaloceanspaces.com"
  datastore.s3.folder: "demo"
  datastore.s3.region: "sgp1"
  datastore.s3.work.folder: "work"
  gateway.api.http.port: "9002"
  gateway.search.timeout.seconds: "120"
  gateway.search.url: "episilia-search:4040"
  indexer.schema.appid.fixed: "defaultApp"
  indexer.schema.appid.keys: "kubernetes.labels.app,release"
  indexer.schema.tenantid.fixed: "defaultTenant"
  indexer.schema.tenantid.keys: ""
  indexer.schema.exclude: "['time']"
  indexer.schema.message.key: "message"
  indexer.schema.timestamp.formats: "%Y-%m-%dT%H:%M:%S"
  indexer.schema.timestamp.key: "time"  
  kafka.group.cpanel: "cpaneld"
  kafka.group.search: "group2"
  kafka.indexer.group: "group1"
  kafka.group.logwatcher: "logwatcher"
  kafka.group.logwatcher.alert: "logwatcher-alert"
  kafka.group.logwatcher.tail: "logwatcher-tail"
  kafka.indexer.logs.topics: "test-log-1"
  kafka.metadata.broker.list: "174.138.123.107:9092"
  kafka.topic.alert.response.out: "alert_out"
  kafka.topic.tail.request.in: "tail_in"
  kafka.topic.tail.response.out: "tail_out"
  kafka.topic.cpanel.out: "cpaneld"
  kafka.topic.index.live: "index"
  kafka.topic.index.optimized: "opt-index"
  kafka.topic.optimize.request: "shivam-opt_req"
  ops.cpanel.data.publish.interval.seconds: "600"
  ops.license.url: "episilia-cpanel:8080"
  ops.log.debug: "true"
  alert.request.file.url: "/episilia-demo/alert/alert_rules.json"
  search.api.grpc.port: "4040"
  search.api.response.max.mb: "100"
  search.api.timeout.seconds: "60"
  search.fixed.from.yyyymmddhh: "2021090100"
  search.fixed.to.yyyymmddhh: "2021122223"
  search.labels.exclude: "['@timestamp', 'log']"
  search.live.from.hours: "48"
  search.live.to.hours: "0"
  search.mode: "live"
  search.ops.index.cache.resetonstart: "true"






